// Code generated by MockGen. DO NOT EDIT.
// Source: user_action_interface.go
//
// Generated by this command:
//
//	mockgen -source=user_action_interface.go -destination=../../test/mock/user/user_action_mock.go -package=user_mock
//

// Package user_mock is a generated GoMock package.
package user_mock

import (
	context "context"
	reflect "reflect"

	user "github.com/fajar3108/lms-backend/internal/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserActionInterface is a mock of UserActionInterface interface.
type MockUserActionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserActionInterfaceMockRecorder
	isgomock struct{}
}

// MockUserActionInterfaceMockRecorder is the mock recorder for MockUserActionInterface.
type MockUserActionInterfaceMockRecorder struct {
	mock *MockUserActionInterface
}

// NewMockUserActionInterface creates a new mock instance.
func NewMockUserActionInterface(ctrl *gomock.Controller) *MockUserActionInterface {
	mock := &MockUserActionInterface{ctrl: ctrl}
	mock.recorder = &MockUserActionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserActionInterface) EXPECT() *MockUserActionInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserActionInterface) CreateUser(ctx context.Context, name, email, password string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, name, email, password)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserActionInterfaceMockRecorder) CreateUser(ctx, name, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserActionInterface)(nil).CreateUser), ctx, name, email, password)
}

// GetUserByEmail mocks base method.
func (m *MockUserActionInterface) GetUserByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserActionInterfaceMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserActionInterface)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserActionInterface) GetUserByID(ctx context.Context, userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserActionInterfaceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserActionInterface)(nil).GetUserByID), ctx, userID)
}
