// Code generated by MockGen. DO NOT EDIT.
// Source: auth_action_interface.go
//
// Generated by this command:
//
//	mockgen -source=auth_action_interface.go -destination=../../test/mock/auth/auth_action_mock.go -package=auth_mock
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"
	time "time"

	user "github.com/fajar3108/lms-backend/internal/user"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthActionInterface is a mock of AuthActionInterface interface.
type MockAuthActionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthActionInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthActionInterfaceMockRecorder is the mock recorder for MockAuthActionInterface.
type MockAuthActionInterfaceMockRecorder struct {
	mock *MockAuthActionInterface
}

// NewMockAuthActionInterface creates a new mock instance.
func NewMockAuthActionInterface(ctrl *gomock.Controller) *MockAuthActionInterface {
	mock := &MockAuthActionInterface{ctrl: ctrl}
	mock.recorder = &MockAuthActionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthActionInterface) EXPECT() *MockAuthActionInterfaceMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockAuthActionInterface) CreateRefreshToken(ctx context.Context, userID, token string, expiresAt time.Time) (*user.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(*user.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockAuthActionInterfaceMockRecorder) CreateRefreshToken(ctx, userID, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockAuthActionInterface)(nil).CreateRefreshToken), ctx, userID, token, expiresAt)
}

// FindRefreshToken mocks base method.
func (m *MockAuthActionInterface) FindRefreshToken(ctx context.Context, token string) (*user.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshToken", ctx, token)
	ret0, _ := ret[0].(*user.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRefreshToken indicates an expected call of FindRefreshToken.
func (mr *MockAuthActionInterfaceMockRecorder) FindRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshToken", reflect.TypeOf((*MockAuthActionInterface)(nil).FindRefreshToken), ctx, token)
}

// RevokeAllUserRefreshTokens mocks base method.
func (m *MockAuthActionInterface) RevokeAllUserRefreshTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserRefreshTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserRefreshTokens indicates an expected call of RevokeAllUserRefreshTokens.
func (mr *MockAuthActionInterfaceMockRecorder) RevokeAllUserRefreshTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserRefreshTokens", reflect.TypeOf((*MockAuthActionInterface)(nil).RevokeAllUserRefreshTokens), ctx, userID)
}

// RotateRefreshToken mocks base method.
func (m *MockAuthActionInterface) RotateRefreshToken(ctx context.Context, userID, oldToken, newToken string, newExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, userID, oldToken, newToken, newExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockAuthActionInterfaceMockRecorder) RotateRefreshToken(ctx, userID, oldToken, newToken, newExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockAuthActionInterface)(nil).RotateRefreshToken), ctx, userID, oldToken, newToken, newExpiresAt)
}
